// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_API.Model
{
    public partial class Accounts
    {
        public int Id { get; set; }
        public string Nick { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public bool? Active_Account { get; set; }
        public DateTime Date_Creation { get; set; }
        public DateTime? Date_Deactivation { get; set; }
    }
}