// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Web_API.Model;

namespace Web_API.Data
{
    public partial class MySomeNameAplicationContext : DbContext
    {
        public MySomeNameAplicationContext()
        {
        }

        public MySomeNameAplicationContext(DbContextOptions<MySomeNameAplicationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Accounts> Accounts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Accounts>(entity =>
            {
                entity.Property(e => e.Active_Account)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Date_Creation)
                    .HasColumnType("date")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Date_Deactivation).HasColumnType("date");

                entity.Property(e => e.Login)
                    .IsRequired()
                    .HasMaxLength(12);

                entity.Property(e => e.Name).HasMaxLength(12);

                entity.Property(e => e.Nick)
                    .IsRequired()
                    .HasMaxLength(12);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(12);

                entity.Property(e => e.Surname).HasMaxLength(12);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}